name: ci-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
jobs:
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - run: |
          brew update && brew install ninja boost openssl automake gcc
          cmake --version
          gcc-13 --version
          uname -a
      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -GNinja \
            -DCMAKE_C_COMPILER="gcc-13" \
            -DCMAKE_CXX_COMPILER="g++-13"
      - name: Build & Test
        run: |
          cd ${{github.workspace}}/build
          ninja -k 5 fibers_test
          ./fibers_test --gtest_repeat=100
